config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end
  
  resources :users, only: [:show, :edit, :update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :user, presence: true

  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where "id IS NOT NULL"}
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_photo, only: [:destroy]

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user

    if @new_photo.save
      EmailNotifyJob.perform_later(@new_photo)
      redirect_to @event, notice: I18n.t('controllers.photos.created')
    else
      render 'events/show', alert: I18n.t('controllers.photos.error')
    end
  end

  def destroy
    message = {notice: I18n.t('controllers.photos.destroyed')}

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = {alert: I18n.t('controllers.photos.error')}
    end
    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end
end

app/views/photos/_form.html.erb
<%= simple_form_for [@event, photo], html: {multipart: true } do |f| %>
  <% render partial: 'partials/form_errors', locals: {model: photo} %>

  	<%= f.input :photo, as: :file %>
  	<%= f.submit t('buttons.upload'), class: 'btn btn-primary' %>
<% end %>

app/views/photos/_photo.html.erb
<% if current_user_can_edit?(photo) %>
  <% delete_photo_btn = link_to("Удалить", event_photo_path(photo.event, photo), method: :delete, data: {confirm: t('.destroy_confirm')}, class: "btn btn-danger") %>
<% end %>

  <%= link_to image_tag(photo.photo.thumb.url), 
      photo.photo.url, 
      data: { toggle: "lightbox",
              gallery: "event-gallery",
              title: "Добавил: #{render partial: 'users/user', object: photo.user }",
              footer: delete_photo_btn } %>
  